### ISSUE TITLE
Typos in magic DRC rules

### ISSUE THREAD

**Issue by rjordans** [efabless/IHP-Open-PDK#6]
## Environment
Code review of 
https://github.com/efabless/IHP-Open-PDK/commit/926543475d94fa3220d6d3c3725268c3390ab149#diff-e1c205f7655013f9abf8f7a24b61b146bd4209732d82078dfcd3168e9a59195dR3523

## Expected Behavior
Rule should check for >= 0.305 um

## Actual Behavior
Implementation shows a check for >= 0.395 um.

The same typo is also in the rules for m3, m4, and m5

**Comment by mole99** [comment]
Hi @rjordans, thanks for your report and for keeping such a close eye on the DRC rules :)
I had to look twice, but I do think the implementation is correct.

For Metal1 the rule M1.e applies:

> Min. space of Metal1 lines if, at least one line is wider than 0.3 µm and the parallel run is more than 1.0 µm

For Metal2 to Metal5 the rule Mn.e applies:

> Min. space of Metal(n) lines if, at least one line is wider than 0.39 µm and the parallel run is more than 1.0 µm

Metal1 is treated differently from the other metal layers, which is easy to overlook.
If you agree, we can close this issue.

**Comment by rjordans** [comment]
Ah, clear, then the rule is implemented correctly indeed but the related error message on the line below may need an update

**Comment by mole99** [comment]
Thanks, I had overlooked those!

Fixed in 0035cc89c74c9c96aaf2a5bdbab6d673ab54fb19
